### ISSUE TITLE
Barcode/QR printer

### ISSUE THREAD

**Issue by dimitrisal** [MatteoMeil/node-native-printer#12]
This is not an issue is more like a question , can this be used with a barcode / qr printer? if yes do we need to change any options??

thanks in advance

**Comment by MatteoMeil** [comment]
I'm sorry for replying so late. I had a intense period of study and work.

If you do not need to have options such as cutting or else relate to thermal printers, yes, you can use with thermal printer.
This package use system's spooler and drivers so is the OS that manage printer. With this package you only set some options and say to the printer what to print.

Anyway, if you're looking something more specific for thermal printers you can take a look at [this google research](https://www.google.com/search?q=node+thermal+priner&oq=node+thermal+priner&aqs=chrome..69i57j0l5.5041j0j7&sourceid=chrome&ie=UTF-8).
