### ISSUE TITLE
Not working with electron-edge-js

### ISSUE THREAD

**Issue by rodrigocvb** [MatteoMeil/node-native-printer#13]
Since I'm using Node 10.X and electron-edge is not compatible with it, I found this package (electron-edge-js) which is. But then my installation refuses to install saying:

electron-edge not found. Trying to find edge.js
edge not found
Installation aborted.

Does anyone has a clue about how should I proceed in this case?

**Comment by MatteoMeil** [comment]
Pushed a commit (https://github.com/MatteoMeil/node-native-printer/commit/c9f922a15dcf9940e0cae0dcee82166b7e89ca70) to add any fork of edge or electron-edge.

I will upload updates on npm soon. Meanwhile you can install this using
```shell
npm i https://github.com/MatteoMeil/node-native-printer.git
```
Take a look at [`README.md`](https://github.com/MatteoMeil/node-native-printer/blob/master/README.md#windows) to see how to install properly this package.

**Comment by ekoeryanto** [comment]
failed when run `electron-builder install-app-deps`
