### ISSUE TITLE
How to print html file

### ISSUE THREAD

**Issue by manhnguyenquoc** [MatteoMeil/node-native-printer#17]
**Describe the bug**
I try to print a html file but it prints like a raw text without rendering any html tags. How can I fix this?

**To Reproduce**
This is my nodejs code:

> printer.setPrinter('SLK-TE203'); 
> printer.print('E:/index.html', {paperSize: 'Custom.270x270', color: false});

This is my html:

![Captur2e](https://user-images.githubusercontent.com/22399058/58776620-a009f680-85f5-11e9-98d4-1aae1c1b4521.PNG)

And the result:
![Untitl2ed](https://user-images.githubusercontent.com/22399058/58776673-cf206800-85f5-11e9-8b6e-28c590e5c2d0.png)

**OS**
 - Windows 10

**Packages**
- edge-js (https://github.com/agracio/edge-js)

**Comment by MatteoMeil** [comment]
node-native-printer is not intended to render and print, but **only to print raw files**.
So, printing an HTML will output raw tags. 

If you need to render your HTML first, you can take a look at [this](https://github.com/dompdf/dompdf) package: you can generate and save a temporary PDF and print it

**Comment by felipe-gustavo** [comment]
@MatteoMeil, has a method to render HTML before print, I want make a feature, but I don't have idea where to start in right method, render HTML in pdf and print the pdf is right method to solve this?

**Comment by MatteoMeil** [comment]
Yes, it's the only method to print a rendered HTML page by now.
This plugin is meant to pront files as-is, so it does not provide any kind
of preprocessing or rendering.
I'm currently non maintaining the repository but I planned to bugfix it and
make some improvement, including HTML rendering, but I don't know when I'll
can.
I'm sorry

Il mar 20 ott 2020, 14:29 Felipe Gustavo <notifications@github.com> ha
scritto:
