### ISSUE TITLE
will this be supported by later version of node ?

### ISSUE THREAD

**Issue by ayami123** [MatteoMeil/node-native-printer#40]
just a question, I want to know if this will still be supported

**Comment by MatteoMeil** [comment]
I am developing a new version of the library with Windows part completely rewritten and also, updating and improving current version.

I don’t have much time thus, the library’s moving really slow. I’m really sorry for that. Hope to upload something soon.

**Comment by catfo435** [comment]
Any update on this @MatteoMeil?
