### ISSUE TITLE
is this suport ECS/POS to print?

### ISSUE THREAD

**Issue by askie** [MatteoMeil/node-native-printer#6]
bluetooth printer need ESC/POST command to print,
is this suport?

**Comment by MatteoMeil** [comment]
No, it only support printing with common printers.
If you need printing with POS printers, take a look to [these](https://www.google.it/search?client=ms-android-om-lge&ei=AgDbW_-3J-qclwTqirXgDw&ins=false&q=node+pos+printer&oq=node+pos+printer&gs_l=mobile-gws-wiz-serp.12..35i39j0i19j0i22i30i19l2.14893.15882..16511...0.0..0.194.975.0j7......0....1.........33i21j33i22i29i30j0i22i30.QJEl9CU7h0U) plugins
