### ISSUE TITLE
can you add edge-js?

### ISSUE THREAD

**Issue by ayami123** [MatteoMeil/node-native-printer#7]
can you add another if in there?
if electron true else if edge else edge-js ?

this is what i did.

before
const edge = require(`../../${process.env.ELECTRON == 'true' ? 'electron-' : ''}edge`);
after
const edge = require(`../../${process.env.ELECTRON == 'true' ? 'electron-' : ''}edge-js`);

but if it will be implemented in here wouldn't it be better if  there are 3 conditions  for electron, edge and edge-js ?

**Comment by ThomasKranitsas** [comment]
@ayami123 I needed support for `electron-edge-js` so I forked this repo and added support for both `edge-js` and `electron-edge-js`.

You can find it here https://github.com/ThomasKranitsas/node-native-printer

@MatteoMeil let me know if you want me to create a PR.

**Comment by MatteoMeil** [comment]
I'm sorry for replaying after so much time.
I didn't know about edge-js. 
If you require it and you want to be included in the plugin, fork this repo, make changes and submit me a PR.
@ThomasKranitsas if you submit a PR I can include your changes. Make sure those changes are stable.

After merging changes i will tag version 1.0.0

**Comment by ThomasKranitsas** [comment]
I'll create a PR once I manage to get it working properly.

Currently, I'm facing this #8

**Comment by MatteoMeil** [comment]
Sorry for a long period of absence due to a lot of work and study

https://github.com/MatteoMeil/node-native-printer/commit/c9f922a15dcf9940e0cae0dcee82166b7e89ca70 solve this issue and #13

I will upload updates on npm soon. Meanwhile you can install this using 
```shell
npm i https://github.com/MatteoMeil/node-native-printer.git
```
